{
 "title": "DBMS Dashboard",
 "tags": [ "DBMS" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request from different ip per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(request_total{instance=~\"$instance\", type=\"ip\"}[1m])",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Different code request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(request_total{instance=~\"$instance\", type=\"code\"}[1m])",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Different method request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(request_total{instance=~\"$instance\", type=\"method\"}[1m])",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Different url request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(request_total{instance=~\"$instance\", type=\"url\", value!=\"/metrics\"}[1m])",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of Interface (quantile=50%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"url\", quantile=\"0.5\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of Interface (quantile=75%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"url\", quantile=\"0.75\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of Interface (quantile=100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"url\", quantile=\"1.0\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of different method request (quantile=50%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"method\", quantile=\"0.5\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of different method request (quantile=75%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"method\", quantile=\"0.75\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Time consumed of different method request (quantile=100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consumed{instance=\"${instance}\", type = \"method\", quantile=\"1.0\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "System CPU Load"
    },
    {
     "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
     "legendFormat": "Process CPU Load"
    }
   ]
  },
  {
   "title": "CPU Time(per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{instance=\"$instance\",name=\"process\"}[1m]))*60",
     "legendFormat": "System CPU Load"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used physical memory"
    },
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "sys_committed_vm_size{instance=\"$instance\"}",
     "legendFormat": "Committed vm size"
    }
   ]
  },
  {
   "title": "System Swap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used Swap Size"
    },
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total Swap Size"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_max_mem{instance=~\"${instance}\"}",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "The Number of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "Young GC number"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "Full GC number"
    }
   ]
  },
  {
   "title": "The Time Consumed Of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "The time of young GC"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "The time of full GC"
    }
   ]
  },
  {
   "title": "The Number Of Java Thread",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "The total number of jvm thread"
    },
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Maximum heap memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
     "legendFormat": "Old area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
     "legendFormat": "Eden area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
     "legendFormat": "Survivor area"
    }
   ]
  },
  {
   "title": "Off Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "off heap memory"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Compilation Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
     "legendFormat": "compiler"
    }
   ]
  },
  {
   "title": "The Number Of Class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Unloaded Number"
    },
    {
     "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Loaded Number"
    }
   ]
  }
 ]
}